import 'package:flutter/widgets.dart';

class ActionItemEntity {
  final ActionGroup group;
  final String name;
  final String imagePath;
  final int dificulty;

  const ActionItemEntity({
    required this.group,
    required this.name,
    required this.imagePath,
    required this.dificulty,
  });

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is ActionItemEntity &&
        other.group == group &&
        other.name == name &&
        other.imagePath == imagePath &&
        other.dificulty == dificulty;
  }

  @override
  int get hashCode {
    return group.hashCode ^ name.hashCode ^ imagePath.hashCode ^ dificulty.hashCode;
  }
}

enum ActionGroup {
  clappingHands,
  jumping,
  running,
  sitting,
  waving,
  throwingBall,
  drinkingWater,
  brushingTeeth,
  sleeping,
  laughing,
  eating,
  readingBook,
  ridingBike,
  hugging,
  walking,
  blowingBubbles,
  drawing,
  kickingBall,
  playingBlocks,
  pettingDog,
  openingDoor,
  closingDoor,
  pouringWater,
  wateringPlants,
  puttingOnHat,
  takingOffHat,
  puttingOnShoes,
  takingOffShoes,
  flippingLightSwitch,
  washingHands,
  blowingNose,
  combingHair,
  foldingClothes,
  makingBed,
  plantingSeeds,
  pushingWheelchair,
  shakingHands,
  holdingHands,
  zippingJacket,
  unzippingJacket,
  buttoningShirt,
  unbuttoningShirt,
  stirringFood,
  cuttingFood,
  sweepingFloor,
  vacuuming,
  wipingTable,
  typingOnKeyboard,
  clickingMouse,
  usingRemoteControl,
  puttingOnGlasses,
  takingOffGlasses,
  paintingPicture,
  playingPiano,
  strummingGuitar,
  writingLetter,
  turningPage,
  sortingShapes,
  slidingPuzzle,
  shakingRattle,
  playingCatch,
  pushingSwing,
  catchingButterfly,
  skippingRope,
  twirlingHulaHoop,
  bouncingBall,
  spinningTop,
  buildingSandcastle,
  blowingOutCandles,
  openingPresent,
  givingGift,
  receivingGift,
  makingWish,
  takingPicture,
  wavingGoodbye,
  scratchingItch,
  yawning,
  sneezing,
  playingVideoGames,
  watchingTV,
  listeningToMusic,
  settingTable,
  clearingTable,
  washingDishes,
  dryingDishes,
  throwingTrash,
  recycling,
  diggingHole,
  rakingLeaves,
  shovelingSnow,
  feedingBirds,
  flyingKite,
  climbingLadder,
  swingingOnSwing,
  slidingDownSlide,
  balancingOnBeam,
  climbingRope,
  crawlingTunnel,
  jumpingPuddles,
  splashingWater,
  pickingFlowers,
  chasingButterflies,
  fishing,
  playingTag,
  whispering,
  shouting,
  singing,
  dancing,
  rollingToyCar,
  stackingCups,
  liftingWeights,
  stretchingArms,
  bendingKnees,
  touchingToes,
  spinningAround,
  balancingOnOneFoot,
  tickling,
  playingPeekABoo,
  marchingInPlace,
  clappingToMusic,
  swayingToMusic,
  hoppingOnOneFoot,
  pointingAtObject,
  wavingFlag,
  turningKnob,
  pullingRope,
  pushingButton,
  openingUmbrella,
  closingUmbrella,
  measuringWithRuler,
  cuttingPaper,
  gluingPaper,
  tyingShoelaces,
  pickingUpToys,
  pushingStroller,
  catchingBall,
  pointing,
  rollingBall,
  swinging,
  sliding,
  climbingStairs,
  coughing,
  rubbingEyes,
  scratchingHead,
  moppingFloor,
  openingWindow,
  closingWindow,
  puttingAwayGroceries,
  bakingCookies,
  flippingPancakes,
  boilingWater,
  peelingFruit,
  slicingBread,
  spreadingButter,
  packingLunch,
  takingOutTrash,
  feedingPet,
  watchingTv,
  listeningToRadio,
  usingComputer,
  playingInstrument,
  gluingCraft,
  stampingEnvelope,
  mailingLetter,
  browsingBookshelf,
  chargingPhone,
  adjustingThermostat,
  hangingPicture,
  measuringDistance,
  hammeringNail,
  tighteningScrew,
  turningKey,
  unlockingDoor,
  lockingDoor,
  carryingGroceries,
  bendingOver,
  twistingBody,
  reachingUp,
  smellingFlowers,
  stylingHair,
  wearingGlasses,
  removingGlasses,
  washingFace,
  applyingLotion,
  puttingOnMakeup,
  removingMakeup,
  wearingBackpack,
  removingBackpack,
  puttingOnBelt,
  takingOffBelt,
  puttingOnGloves,
  takingOffGloves,
  puttingOnJacket,
  takingOffJacket,
  puttingOnScarf,
  takingOffScarf,
  puttingOnSocks,
  takingOffSocks,
  puttingOnSweater,
  takingOffS
}

extension ActionGroupNameEx on ActionGroup {
  String actionName(BuildContext context) {
    return 'action';
  }
}
