import 'package:flutter/widgets.dart';

class ActionItemEntity {
  final ActionGroup group;
  final String name;
  final String imagePath;
  final int dificulty;

  const ActionItemEntity({
    required this.group,
    required this.name,
    required this.imagePath,
    required this.dificulty,
  });

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is ActionItemEntity &&
        other.group == group &&
        other.name == name &&
        other.imagePath == imagePath &&
        other.dificulty == dificulty;
  }

  @override
  int get hashCode {
    return group.hashCode ^ name.hashCode ^ imagePath.hashCode ^ dificulty.hashCode;
  }
}

enum ActionGroup {
  adjustingThermostat,
  adoptingPet,
  answeringPhone,
  applyingLotion,
  bakingCookies,
  balancingOnBeam,
  balancingOnOneFoot,
  bathing,
  bendingKnees,
  bendingOver,
  blowingBubbles,
  blowingNose,
  blowingOutCandles,
  boilingWater,
  bouncingBall,
  bowling,
  browsingBookshelf,
  brushingHair,
  brushingTeeth,
  buildingSandcastle,
  buttoningShirt,
  callingFriend,
  canoeing,
  caringForPet,
  carryingGroceries,
  catchingBall,
  catchingButterfly,
  chargingPhone,
  chasingButterflies,
  clappingHands,
  clappingToMusic,
  clearingTable,
  clickingMouse,
  climbingLadder,
  climbingRope,
  climbingStairs,
  climbingTree,
  closingDoor,
  closingUmbrella,
  closingWindow,
  coloring,
  combingHair,
  cooking,
  coughing,
  crawlingTunnel,
  crossingStreet,
  custom,
  cuttingFood,
  cuttingPaper,
  dancing,
  diggingHole,
  diggingSand,
  drawing,
  drinkingWater,
  drivingCar,
  dryingDishes,
  eating,
  eatingMeal,
  feedingBirds,
  feedingPet,
  fishing,
  flippingLightSwitch,
  flippingPancakes,
  flyingKite,
  foldingClothes,
  foldingLaundry,
  givingGift,
  gluingCraft,
  gluingPaper,
  goingDoctor,
  goingPark,
  goingStore,
  goingZoo,
  graspingObject,
  greetingSomeone,
  hammeringNail,
  hangingPicture,
  hiding,
  holdingHands,
  hoppingOnOneFoot,
  hugging,
  huggingSomeone,
  jumping,
  jumpingPuddles,
  jumpingRope,
  kickingBall,
  laughing,
  liftingWeights,
  listeningToMusic,
  listeningToRadio,
  lockingDoor,
  mailingLetter,
  makingBed,
  makingFriend,
  makingSandwich,
  makingWish,
  marchingInPlace,
  measuringDistance,
  measuringWithRuler,
  meditating,
  meetingNewPeople,
  moppingFloor,
  mowingLawn,
  openingDoor,
  openingPresent,
  openingUmbrella,
  openingWindow,
  packingLunch,
  paintingPicture,
  peelingFruit,
  pettingDog,
  pickingFlowers,
  pickingUpToys,
  plantingSeeds,
  playingBlocks,
  playingCatch,
  playingGame,
  playingInSnow,
  playingInstrument,
  playingPeekABoo,
  playingPiano,
  playingTag,
  playingVideoGames,
  playingWithPet,
  pointing,
  pointingAtObject,
  pouringWater,
  pullingRope,
  pushingButton,
  pushingStroller,
  pushingSwing,
  pushingWheelchair,
  puttingAwayGroceries,
  puttingOnBelt,
  puttingOnGlasses,
  puttingOnGloves,
  puttingOnHat,
  puttingOnJacket,
  puttingOnMakeup,
  puttingOnScarf,
  puttingOnShoes,
  puttingOnSocks,
  puttingOnSweater,
  rakingLeaves,
  reachingUp,
  readingBook,
  receivingGift,
  recycling,
  removingBackpack,
  removingGlasses,
  removingMakeup,
  ridingBike,
  ridingElevator,
  ridingHorse,
  rollingBall,
  rollingToyCar,
  rubbingEyes,
  running,
  runningRace,
  sailing,
  scratchingHead,
  scratchingItch,
  scubaDiving,
  settingTable,
  shakingHands,
  shakingRattle,
  shouting,
  shovelingSnow,
  singing,
  sitting,
  skiing,
  skippingRope,
  sleeping,
  slicingBread,
  sliding,
  slidingDownSlide,
  slidingPuzzle,
  smellingFlowers,
  sneezing,
  solvingPuzzle,
  sortingShapes,
  spinningAround,
  spinningTop,
  splashingWater,
  spreadingButter,
  stackingCups,
  stampingEnvelope,
  stirringFood,
  stretchingArms,
  strummingGuitar,
  stylingHair,
  swayingToMusic,
  sweepingFloor,
  swimming,
  swinging,
  swingingOnSwing,
  takingBath,
  takingOffBelt,
  takingOffGlasses,
  takingOffGloves,
  takingOffHat,
  takingOffJacket,
  takingOffS,
  takingOffScarf,
  takingOffShoes,
  takingOffSocks,
  takingOutTrash,
  takingPicture,
  takingShower,
  talkingOnPhone,
  tearingUpPaper,
  throwingBall,
  throwingTrash,
  tickling,
  tighteningScrew,
  touchingToes,
  turningKey,
  turningKnob,
  turningPage,
  twirlingHulaHoop,
  twistingBody,
  tyingShoelace,
  tyingShoelaces,
  typingOnKeyboard,
  unbuttoningShirt,
  unlockingDoor,
  unzippingJacket,
  usingComputer,
  usingRemoteControl,
  vacuuming,
  walking,
  walkingDog,
  washingDishes,
  washingFace,
  washingHands,
  watchingMovie,
  watchingTV,
  wateringPlants,
  waving,
  wavingFlag,
  wavingGoodbye,
  wearingBackpack,
  wearingGlasses,
  whispering,
  wipingTable,
  writingLetter,
  yawning,
  yelling,
  zippingJacket,
}

extension ActionGroupNameEx on ActionGroup {
  String actionName(BuildContext context) {
    return 'action';
  }
}
